---
# Install Vector
- name: Install Vector packages (deb)
  become: true
  ansible.builtin.deb:
    name: vector_{{ vector_version }}-1.{{ ansible_architecture }}.deb
    state: present
  notify: Start Vector service
- name: Creates directory
  become: true
  file:
    path: /var/lib/vector/local_logs
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
  notify: Start Vector service
