---
# Install Vector
- name: Install Vector packages (dnf)
  become: true
  ansible.builtin.dnf:
    name: vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm
    state: present
  notify: Start Vector service

