---
# tasks file for vector-role
- name: Get Vector distrib
  import_tasks: download/{{ ansible_pkg_mgr }}.yml

- name: Install Vector packages
  import_tasks: install/{{ ansible_pkg_mgr }}.yml

- name: Deploy config Vector
  import_tasks: configure.yml
