---
# Dounload vector files
- name: Get Vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm"
    dest: "./vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm"
    mode: 0644
